export const InputFileTypes = [
  "Select",
  "FIR",
  "482",
  "Complaint",
  "Charge Sheet",
  "Order",
  "Notice",
  "Petition",
  "Written Statement",
  "Judgement",
  "Order sheet",
  "Written Petition",
  "Response to Appeals",
  "OCR",
];

export const OutputTypes = [
  { name: "Select", disabled: false },
  { name: "appeal", disabled: false },
  { name: "petition", disabled: false },
  { name: "written_statement", disabled: false },
  { name: "482", disabled: false },
  { name: "writ_petition", disabled: false },
  { name: "impleading_application", disabled: false },
  { name: "injunction_app", disabled: false },
  { name: "criminal_appeal", disabled: true },
  { name: "response_to_appeal", disabled: true },
  { name: "notices", disabled: false },
  { name: "revision_petition", disabled: true },
  { name: "criminal_petition", disabled: true },
  { name: "criminal_complaint", disabled: true },
  { name: "consumer_complaint", disabled: true },
  { name: "version_consumercourts", disabled: true },
  { name: "translations", disabled: false },
  { name: "summarisations", disabled: false },
  { name: "ocr", disabled: false },
];
